name: Cyberbessa Vanilla Desktop
id: desktop

stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main
  singlelayer: false

  labels:
    maintainer: self-maintained

  args:
    DEBIAN_FRONTEND: noninteractive

  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
      - lpkg --unlock
      - apt-get update

  - name: basic-packages
    type: apt
    source:
      packages:
        - fastfetch
        - btop
        - curl
        - wget
        - zip
        - git
        - gnome-tweaks

  - name: flatpaks
    type: flatpak
    system:
      repourl: https://flathub.org/repo/flathub.flatpakrepo
      reponame: flathub
      install:
        - io.github.ungoogled_software.ungoogled_chromium
        - org.gnome.gitlab.somas.Apostrophe
        - app.zen_browser.zen
        - com.slack.Slack
        - com.discordapp.Discord
        - it.mijorus.smile
        - be.alexandervanhee.gradia
        - com.vscodium.codium
        - eu.betterbird.Betterbird
        - com.bitwarden.desktop
        - io.github.pwr_solaar.solaar
        - dev.deedles.Trayscale
        - com.spotify.Client
        - com.surfshark.Surfshark
        - com.github.jkotra.eovpn
        - org.onlyoffice.desktopeditors
        - io.missioncenter.MissionCenter
        - app.drey.Warp
        - com.mattjakeman.ExtensionManager
        - io.github.vikdevelop.SaveDesktop
        - org.mozilla.firefox
        - com.usebottles.bottles
        - io.github.swordpuffin.rewaita

  - name: keybindings-and-adjustments-on-first-login
    type: shell
    commands:
      - |
        #!/usr/bin/env sh
        set -eu
        
        MARKER="$HOME/.config/.gnome-first-login-done"
        
        # Run once per user
        if [ -f "$MARKER" ]; then
          exit 0
        fi
        
        echo "[GNOME First Login] Applying user configuration…"
        
        # Enable fractional scaling
        gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"
        
        # Close window keybind
        dconf write /org/gnome/desktop/wm/keybindings/close "['<Super>q', '<Alt>F4']"
        
        # Declare custom keybindings
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings "[
          '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/',
          '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/',
          '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/',
          '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/',
          '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/'
        ]"
        
        # Nautilus
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name "'Nautilus'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command "'nautilus --new-window'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding "'<Super>e'"
        
        # Terminal
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name "'Blackbox Terminal'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command "'blackbox-terminal'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding "'<Super>t'"
        
        # Emojis
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name "'Emojis'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command "'flatpak run it.mijorus.smile'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding "'<Super>.'"
        
        # Gradia
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/name "'Gradia Screenshot Utility'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/command "'flatpak run be.alexandervanhee.gradia --screenshot'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/binding "'<Super>Print'"
        
        # Firefox
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/name "'Firefox'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/command "'flatpak run org.mozilla.firefox'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/binding "'<Super>w'"
        
        # Allow Rewaita colors to Flatpak apps
        flatpak override --user --filesystem=xdg-config/gtk-4.0:ro
        flatpak override --user --filesystem=xdg-config/gtk-3.0:ro
        
        mkdir -p "$HOME/.config"
        touch "$MARKER"
        
        echo "[GNOME First Login] Configuration applied successfully."


      - |
        # Install systemd user service (runs once at first login)
        install -Dm644 /dev/stdin /etc/skel/.config/systemd/user/gnome-first-login.service << 'EOF'
        [Unit]
        Description=GNOME first login user configuration
        After=graphical-session.target

        [Service]
        Type=oneshot
        ExecStart=/usr/local/bin/gnome-first-login.sh
        ConditionPathExists=!%h/.config/.gnome-first-login-done

        [Install]
        WantedBy=default.target
        EOF


  - name: set-image-name-abroot
    type: includes
    includes:
      - modules/80-set-image-abroot-config.yml

  - name: cleanup
    type: shell
    commands:
      - apt-get autoremove -y
      - apt-get clean
      - lpkg --lock

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: /usr/sbin/FsGuard
    GenerateKey: true
    FilelistPaths:
      - /usr/bin
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard
          - rm -f ./minisign.pub ./minisign.key
          - chmod +x /usr/sbin/init

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
